import type { Metadata } from "next";
import localFont from "next/font/local";
import { Providers } from "./providers";
import "./globals.css";
import CollapsibleSidebar from "@/components/collapsible-sidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className=''>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          {/* <CollapsibleSidebar/>
          <main className="flex-1">
            {/* Main content goes here 
          {children}
        </main>
         */}

          <div className="flex h-screen flex-nowrap">
            <CollapsibleSidebar />
            <main className="flex-1 min-w-0 h-full overflow-auto">
              {/* Main content goes here */}
              {children}
            </main>
          </div>
        </Providers>
      </body>
    </html >
  )
}

